### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by NoelBradford** [jheyman/videosurveillance#1]
```
Traceback (most recent call last):
  File "surveillance.py", line 9, in <module>
    import cv
ImportError: No module named cv
```

Installed OpenCV so not sure where next?

**Comment by jheyman** [comment]
Hi Noel,

Somehow python does not pick up your openCV install. For this project, at the time I just had to do this:

sudo apt-get install libopencv-dev python-opencv

and the cv import in python worked fine. 
(see http://jheyman.github.io/blog/pages/VideoSurveillance/#installing-opencv )

**Comment by NoelBradford** [comment]
Thanks that fixed it...

Great work.
